# Generated by Django 2.1.2 on 2019-10-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line_status', '0002_linestatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestatus',
            name='delayed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
