# Generated by Django 2.1.2 on 2019-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_status', '0004_auto_20191008_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestatus',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
