# Generated by Django 2.1.2 on 2019-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_status', '0005_auto_20191008_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
